version: 2
jobs:
  app_test:
    docker:
      - image: circleci/node:8.14.0

    working_directory: ~/openchs-webapp

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: yarn test

  app_build:
    docker:
      - image: circleci/node:8.14.0

    working_directory: ~/openchs-webapp

    steps:
        - checkout

        - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}

        - run: yarn install

        - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
              - ./node_modules

        - run: yarn run build


workflows:
  version: 2
  test_and_build:
    jobs:
      - app_test
      - app_build:
          requires:
            - app_test


notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/0fdffde721194986f2a0


